### ISSUE TITLE
Use 64-bit int for hardware id

### ISSUE THREAD

**Issue by rychipman** [solsensor/sol#2]
Currently, we use a 32-bit int for the hardware id, but the hardware id is actually 64 bits. We should change this so that we can create sensors with their actual hardware ids

**Comment by rychipman** [comment]
@jwachlin is the hardware_id a uint64 or an int64 (I'm assuming the former, but just want to check)

**Comment by jwachlin** [comment]
Uint64 in firmware

**Comment by rychipman** [comment]
fixed
